extra:
  search:
    language: 'en, pt'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences

nav:
- Introdução: index.md
- LEIAME: LEIAME.md
- Aula 1 (2019-04-05): aula1.md
- Aula 2 (2019-04-08): aula2.md
- Aula 3 (2019-04-16): aula3.md
- Aula 4 (2019-04-19): aula4.md
- Exercícios 1: exercicios1.md
- Exercícios 2: exercicios2.md
- FOR: for.md

plugins:
  - search

site_name: Algoritmos e estruturas de dados
site_description: Disciplina algoritmos e estruturas de dados
site_author: Allainclair Flausino dos Santos
site_url: https://github.com/allainclair

theme:
  language: pt
  name: material
